// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ntttrang/go-genai-slack-assistant/internal/service (interfaces: EventProcessorService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEventProcessorService is a mock of EventProcessorService interface.
type MockEventProcessorService struct {
	ctrl     *gomock.Controller
	recorder *MockEventProcessorServiceMockRecorder
}

// MockEventProcessorServiceMockRecorder is the mock recorder for MockEventProcessorService.
type MockEventProcessorServiceMockRecorder struct {
	mock *MockEventProcessorService
}

// NewMockEventProcessorService creates a new mock instance.
func NewMockEventProcessorService(ctrl *gomock.Controller) *MockEventProcessorService {
	mock := &MockEventProcessorService{ctrl: ctrl}
	mock.recorder = &MockEventProcessorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventProcessorService) EXPECT() *MockEventProcessorServiceMockRecorder {
	return m.recorder
}

// ProcessEvent mocks base method.
func (m *MockEventProcessorService) ProcessEvent(arg0 context.Context, arg1 map[string]interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessEvent", arg0, arg1)
}

// ProcessEvent indicates an expected call of ProcessEvent.
func (mr *MockEventProcessorServiceMockRecorder) ProcessEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessEvent", reflect.TypeOf((*MockEventProcessorService)(nil).ProcessEvent), arg0, arg1)
}
