// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ntttrang/go-genai-slack-assistant/internal/service (interfaces: ChannelService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/ntttrang/go-genai-slack-assistant/internal/model"
)

// MockChannelService is a mock of ChannelService interface.
type MockChannelService struct {
	ctrl     *gomock.Controller
	recorder *MockChannelServiceMockRecorder
}

// MockChannelServiceMockRecorder is the mock recorder for MockChannelService.
type MockChannelServiceMockRecorder struct {
	mock *MockChannelService
}

// NewMockChannelService creates a new mock instance.
func NewMockChannelService(ctrl *gomock.Controller) *MockChannelService {
	mock := &MockChannelService{ctrl: ctrl}
	mock.recorder = &MockChannelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelService) EXPECT() *MockChannelServiceMockRecorder {
	return m.recorder
}

// CreateChannelConfig mocks base method.
func (m *MockChannelService) CreateChannelConfig(arg0 *model.ChannelConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChannelConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateChannelConfig indicates an expected call of CreateChannelConfig.
func (mr *MockChannelServiceMockRecorder) CreateChannelConfig(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChannelConfig", reflect.TypeOf((*MockChannelService)(nil).CreateChannelConfig), arg0)
}

// DeleteChannelConfig mocks base method.
func (m *MockChannelService) DeleteChannelConfig(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChannelConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChannelConfig indicates an expected call of DeleteChannelConfig.
func (mr *MockChannelServiceMockRecorder) DeleteChannelConfig(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChannelConfig", reflect.TypeOf((*MockChannelService)(nil).DeleteChannelConfig), arg0)
}

// GetChannelConfig mocks base method.
func (m *MockChannelService) GetChannelConfig(arg0 string) (*model.ChannelConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelConfig", arg0)
	ret0, _ := ret[0].(*model.ChannelConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelConfig indicates an expected call of GetChannelConfig.
func (mr *MockChannelServiceMockRecorder) GetChannelConfig(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelConfig", reflect.TypeOf((*MockChannelService)(nil).GetChannelConfig), arg0)
}

// IsChannelEnabled mocks base method.
func (m *MockChannelService) IsChannelEnabled(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsChannelEnabled", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsChannelEnabled indicates an expected call of IsChannelEnabled.
func (mr *MockChannelServiceMockRecorder) IsChannelEnabled(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsChannelEnabled", reflect.TypeOf((*MockChannelService)(nil).IsChannelEnabled), arg0)
}

// ListAllChannelConfigs mocks base method.
func (m *MockChannelService) ListAllChannelConfigs() ([]*model.ChannelConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllChannelConfigs")
	ret0, _ := ret[0].([]*model.ChannelConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllChannelConfigs indicates an expected call of ListAllChannelConfigs.
func (mr *MockChannelServiceMockRecorder) ListAllChannelConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllChannelConfigs", reflect.TypeOf((*MockChannelService)(nil).ListAllChannelConfigs))
}

// UpdateChannelConfig mocks base method.
func (m *MockChannelService) UpdateChannelConfig(arg0 *model.ChannelConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChannelConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChannelConfig indicates an expected call of UpdateChannelConfig.
func (mr *MockChannelServiceMockRecorder) UpdateChannelConfig(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChannelConfig", reflect.TypeOf((*MockChannelService)(nil).UpdateChannelConfig), arg0)
}
