// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ntttrang/go-genai-slack-assistant/internal/service (interfaces: TranslationRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/ntttrang/go-genai-slack-assistant/internal/model"
)

// MockTranslationRepository is a mock of TranslationRepository interface.
type MockTranslationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationRepositoryMockRecorder
}

// MockTranslationRepositoryMockRecorder is the mock recorder for MockTranslationRepository.
type MockTranslationRepositoryMockRecorder struct {
	mock *MockTranslationRepository
}

// NewMockTranslationRepository creates a new mock instance.
func NewMockTranslationRepository(ctrl *gomock.Controller) *MockTranslationRepository {
	mock := &MockTranslationRepository{ctrl: ctrl}
	mock.recorder = &MockTranslationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationRepository) EXPECT() *MockTranslationRepositoryMockRecorder {
	return m.recorder
}

// GetByChannelID mocks base method.
func (m *MockTranslationRepository) GetByChannelID(arg0 string, arg1 int) ([]*model.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByChannelID", arg0, arg1)
	ret0, _ := ret[0].([]*model.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByChannelID indicates an expected call of GetByChannelID.
func (mr *MockTranslationRepositoryMockRecorder) GetByChannelID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByChannelID", reflect.TypeOf((*MockTranslationRepository)(nil).GetByChannelID), arg0, arg1)
}

// GetByHash mocks base method.
func (m *MockTranslationRepository) GetByHash(arg0 string) (*model.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", arg0)
	ret0, _ := ret[0].(*model.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockTranslationRepositoryMockRecorder) GetByHash(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockTranslationRepository)(nil).GetByHash), arg0)
}

// GetByID mocks base method.
func (m *MockTranslationRepository) GetByID(arg0 string) (*model.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0)
	ret0, _ := ret[0].(*model.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTranslationRepositoryMockRecorder) GetByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTranslationRepository)(nil).GetByID), arg0)
}

// Save mocks base method.
func (m *MockTranslationRepository) Save(arg0 *model.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockTranslationRepositoryMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockTranslationRepository)(nil).Save), arg0)
}
