// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ntttrang/go-genai-slack-assistant/internal/service (interfaces: TranslationService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	request "github.com/ntttrang/go-genai-slack-assistant/internal/dto/request"
	response "github.com/ntttrang/go-genai-slack-assistant/internal/dto/response"
)

// MockTranslationService is a mock of TranslationService interface.
type MockTranslationService struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationServiceMockRecorder
}

// MockTranslationServiceMockRecorder is the mock recorder for MockTranslationService.
type MockTranslationServiceMockRecorder struct {
	mock *MockTranslationService
}

// NewMockTranslationService creates a new mock instance.
func NewMockTranslationService(ctrl *gomock.Controller) *MockTranslationService {
	mock := &MockTranslationService{ctrl: ctrl}
	mock.recorder = &MockTranslationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationService) EXPECT() *MockTranslationServiceMockRecorder {
	return m.recorder
}

// DetectLanguage mocks base method.
func (m *MockTranslationService) DetectLanguage(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectLanguage", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetectLanguage indicates an expected call of DetectLanguage.
func (mr *MockTranslationServiceMockRecorder) DetectLanguage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectLanguage", reflect.TypeOf((*MockTranslationService)(nil).DetectLanguage), arg0)
}

// Translate mocks base method.
func (m *MockTranslationService) Translate(arg0 request.Translation) (response.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", arg0)
	ret0, _ := ret[0].(response.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationServiceMockRecorder) Translate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationService)(nil).Translate), arg0)
}
